### ISSUE TITLE
Error when prereq script finishes on a9

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/gluex_install#58]
gluex_prereqs_almalinux_9.sh ends with this message
```
Complete!
ln: failed to create symbolic link 'freetype/freetype': File exists
./gluex_prereqs_almalinux_9.sh: line 22: /gluex_install/gluex_prereqs_postprocessor.sh: No such file or directory
```

**Comment by aaust** [comment]
The second line only make sense in a container. We should check, for example  if `/.singularity.d` or `/.dockerenv` are present before running the postprocessor.

**Comment by aaust** [comment]
Please check this branch: [aaust_almalinux9_prereq](https://github.com/JeffersonLab/gluex_install/tree/aaust_almalinux9_prereq)
It was not as easy as my suggestion above, as the script has to detect a docker build.

**Comment by nsjarvis** [comment]
Fixed.  I still see this line "ln: failed to create symbolic link 'freetype/freetype': File exists"
but it looks harmless.  The more worrying line about the postprocessor has gone. 
Thank you.
